import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#0C0E10",
  },
  container: {
    flex: 1,
    justifyContent: "space-between",
    paddingHorizontal: 24,
    paddingVertical: 48,
  },
  backgroundGlowTop: {
    position: "absolute",
    top: -100,
    left: 0,
    right: 0,
    height: 500,
    width: 500,
    alignSelf: "center",
    borderRadius: 250,
  },
  backgroundGlowBottom: {
    position: "absolute",
    bottom: -150,
    right: -150,
    height: 300,
    width: 300,
    borderRadius: 150,
  },
  topSection: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    maxWidth: 384,
    alignSelf: "center",
  },
  brandContainer: {
    alignItems: "center",
    marginBottom: 48,
  },
  logoBackground: {
    width: 80,
    height: 80,
    borderRadius: 16,
    backgroundColor: "#1A1D20",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 24,
  },
  title: {
    fontSize: 28,
    fontWeight: "bold",
    letterSpacing: -0.5,
    color: "#EAEAEA",
  },
  subtitle: {
    fontSize: 14,
    fontWeight: "500",
    letterSpacing: 4,
    color: "#A0A0A0",
    marginTop: 4,
    textTransform: "uppercase",
  },
  description: {
    textAlign: "center",
    color: "#A0A0A0",
    fontSize: 16,
    lineHeight: 24,
    marginBottom: 40,
    maxWidth: 320,
  },
  featuresContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 12,
    marginBottom: 48,
  },
  featurePill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: "rgba(26, 29, 32, 0.8)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  featureLabel: {
    fontSize: 12,
    fontWeight: "500",
    color: "#D4D4D8",
  },
  bottomSection: {
    width: "100%",
    maxWidth: 384,
    alignSelf: "center",
    gap: 16,
  },
  ctaButton: {
    width: "100%",
    height: 56,
    backgroundColor: "#38A7B5",
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  ctaButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#FFFFFF",
  },
  logoImage: {
    width: 70,
    height: 70,
    resizeMode: "contain",
    marginBottom: 16,
    borderRadius: 10,
  },
});

export default styles;
