import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0C0E10",
    justifyContent: "center",
  },
  backgroundGlowTop: {
    position: "absolute",
    top: -100,
    left: 0,
    right: 0,
    height: 500,
    width: 500,
    alignSelf: "center",
    borderRadius: 250,
  },
  backgroundGlowBottom: {
    position: "absolute",
    bottom: -150,
    right: -150,
    height: 300,
    width: 300,
    borderRadius: 150,
  },
  keyboardView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  logoPlaceholder: {
    width: 60,
    height: 60,
    borderRadius: 12,
    backgroundColor: "#1E293B",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 30,
    overflow: "hidden",
  },
  title: {
    fontSize: 28,
    fontWeight: "600",
    color: "#F0F0F0",
  },
  subtitle: {
    fontSize: 14,
    color: "#A0A0A0",
    marginTop: 5,
    letterSpacing: 1,
    marginBottom: 30,
  },
  instructionText: {
    fontSize: 15,
    color: "#E0E0E0",
    textAlign: "center",
    lineHeight: 22,
    marginBottom: 30,
    maxWidth: 300,
  },
  label: {
    fontSize: 14,
    fontWeight: "600",
    color: "#CBD5E1",
    marginBottom: 8,
    alignSelf: "flex-start",
  },
  inputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#000",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 8,
    height: 50,
    paddingHorizontal: 15,
    width: "100%",
  },
  inputGroup: { width: "100%", marginBottom: 20 },
  icon: { marginRight: 10 },
  input: {
    flex: 1,
    height: "100%",
    color: "#fff",
    fontSize: 16,
    borderWidth: 0,
    backgroundColor: "transparent",
    paddingHorizontal: 0,
  },
  submitButton: {
    width: "100%",
    height: 50,
    backgroundColor: "#38A7B5",
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 10,
  },
  submitButtonText: {
    color: "#FFFFFF",
    fontSize: 17,
    fontWeight: "600",
  },
  footer: {
    width: "100%",
    alignItems: "center",
    marginTop: 40,
  },
  backToLoginLink: {
    color: "#6DA0CC",
    fontSize: 15,
    fontWeight: "500",
    marginBottom: 20,
  },
  logoImage: {
    width: "100%",
    height: "100%",
    resizeMode: "contain",
  },
});

export default styles;
