import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0b0f14",
    paddingHorizontal: 16,
  },
  headerContainer: {
    marginTop: 12,
    marginBottom: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  menuButton: {
    width: 40,
    height: 40,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
  },
  headerTitles: {
    flex: 1,
    minWidth: 0,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#ffffff",
  },
  headerSubtitle: {
    fontSize: 13,
    color: "#9ca3af",
    marginTop: 2,
  },
  scrollContent: {
    paddingBottom: 90,
  },
  card: {
    backgroundColor: "#121821",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#1f2937",
    padding: 16,
    marginBottom: 16,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  cardDateContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  cardDateText: {
    fontSize: 14,
    color: "#ffffff",
    fontWeight: "600",
  },
  badge: {
    backgroundColor: "#1f2937",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#374151",
  },
  badgeText: {
    fontSize: 11,
    color: "#9ca3af",
    fontWeight: "500",
  },
  statsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#1f2937",
    marginBottom: 12,
  },
  statItem: {
    alignItems: "center",
    flex: 1,
  },
  statValue: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#ffffff",
    marginTop: 4,
  },
  statLabel: {
    fontSize: 10,
    color: "#6b7280",
    marginTop: 2,
  },
  performanceContainer: {
    marginBottom: 16,
  },
  performanceText: {
    fontSize: 13,
    color: "#9ca3af",
  },
  performanceValue: {
    color: "#ffffff",
    fontWeight: "bold",
  },
  annotationsText: {
    fontSize: 12,
    color: "#9ca3af",
    marginTop: 4,
    fontStyle: "italic",
  },
  cardActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 16,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#1f2937",
  },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  actionText: {
    fontSize: 12,
    color: "#9ca3af",
  },
  footerContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    padding: 16,
    backgroundColor: "#0b0f14",
    borderTopWidth: 1,
    borderTopColor: "#1f2937",
  },
  registerButton: {
    backgroundColor: "#2e7d9c",
    height: 48,
    borderRadius: 12,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
  },
  registerButtonText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "600",
  },
  backgroundGlowTop: {
    position: "absolute",
    top: -100,
    left: 0,
    right: 0,
    height: 500,
    width: 500,
    alignSelf: "center",
    borderRadius: 250,
  },
  backgroundGlowBottom: {
    position: "absolute",
    bottom: -150,
    right: -150,
    height: 300,
    width: 300,
    borderRadius: 150,
  },
});
