import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0b0f19",
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 100,
  },
  backButton: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  backText: {
    color: "#9ca3af",
    fontSize: 16,
    marginLeft: 6,
  },
  headerContainer: {
    marginBottom: 20,
  },
  title: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#ffffff",
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 14,
    color: "#9ca3af",
  },
  statsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  statCard: {
    flex: 1,
    backgroundColor: "#111827",
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 8,
    alignItems: "center",
    marginHorizontal: 4,
    borderWidth: 1,
    borderColor: "#1f2937",
  },
  statValue: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#ffffff",
    marginTop: 8,
    textAlign: "center",
  },
  statLabel: {
    fontSize: 11,
    color: "#9ca3af",
    marginTop: 4,
  },
  sectionBox: {
    backgroundColor: "#111827",
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#1f2937",
  },
  sectionTitle: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#9ca3af",
    letterSpacing: 1,
    marginBottom: 8,
  },
  sectionContentValue: {
    fontSize: 16,
    color: "#ffffff",
    fontWeight: "600",
  },
  notesText: {
    fontSize: 14,
    color: "#9ca3af",
    marginTop: 8,
  },
  rollsSectionHeader: {
    marginBottom: 10,
  },
  noRollsText: {
    color: "#9ca3af",
    fontSize: 14,
    fontStyle: "italic",
    marginBottom: 20,
  },
  rollCard: {
    backgroundColor: "#111827",
    borderRadius: 10,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#1f2937",
  },
  rollPartner: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 14,
    marginBottom: 4,
  },
  rollDetails: {
    color: "#9ca3af",
    fontSize: 12,
    marginTop: 2,
  },
  footerContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#0b0f19",
    flexDirection: "row",
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: "#1f2937",
  },
  editButton: {
    flex: 1,
    backgroundColor: "#2dd4bf",
    flexDirection: "row",
    height: 48,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  editButtonText: {
    color: "#0f172a",
    fontSize: 16,
    fontWeight: "bold",
    marginLeft: 8,
  },
  deleteButton: {
    width: 48,
    height: 48,
    backgroundColor: "#111827",
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#ef4444",
  },
  backgroundGlowTop: {
    position: "absolute",
    top: -100,
    left: 0,
    right: 0,
    height: 500,
    width: 500,
    alignSelf: "center",
    borderRadius: 250,
  },
  backgroundGlowBottom: {
    position: "absolute",
    bottom: -150,
    right: -150,
    height: 300,
    width: 300,
    borderRadius: 150,
  },
});